[package]
name = "mirror-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tempfile = "3.14"
